---
- name: Create Docker Group and Add User
  hosts: dockerUbuntu
  become: yes
  tasks:
    - name: Create the docker group
      group:
        name: docker
        state: present

    - name: Add your user to the docker group
      user:
        name: test
        groups: docker
        append: yes
